dependencies {
    api project(':module:domain')
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // 낙관적 락(@Version) 충돌 재시도용 — @OptimisticLockRetry(@Retryable) 지원
    // @Retryable 은 Spring AOP 프록시로 동작하므로 spring-aop(스프링 컨텍스트 전이) 만으로 충분.
    // Source: https://mvnrepository.com/artifact/org.springframework.retry/spring-retry
    implementation "org.springframework.retry:spring-retry:2.0.12"

    implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
}
