DROP TABLE IF EXISTS daily_product_sales_stat;
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id BIGINT PRIMARY KEY,
    ordered_at TIMESTAMP NOT NULL,
    product_id BIGINT NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE INDEX idx_orders_ordered_at ON orders (ordered_at);
CREATE INDEX idx_orders_product_ordered_at ON orders (product_id, ordered_at);
CREATE INDEX idx_orders_status_ordered_at ON orders (status, ordered_at);

CREATE TABLE daily_product_sales_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stat_date DATE NOT NULL,
    product_id BIGINT NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    order_count BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_daily_product_sales_stat UNIQUE (stat_date, product_id)
);

CREATE INDEX idx_daily_product_sales_stat_stat_date
    ON daily_product_sales_stat (stat_date);
