spring:
  application:
    name: order-service
  config:
    import: "${CONFIG_SERVER_URL:optional:configserver:http://localhost:8888}"

eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_URL:http://localhost:8761/eureka}"

management:
  endpoints:
    web:
      exposure:
        include: health,info
