spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: true
      file: ./spring_elk/docker-compose.yaml
      lifecycle-management: start-and-stop

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha



