plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':module:core:core-web')
    implementation project(':module:jwt-auth')
    implementation project(':module:business-logic')
    implementation project(':module:tools:metrics')
    implementation project(':module:tools:log-elk')

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.security:spring-security-test'
}