server:
  port: 8081

spring:
  application:
    name: app-client

  boot:
    admin:
      client:
        url: "http://localhost:18080"
        instance:
          # 서버에서 보일 주소/호스트 이름 지정
          prefer-ip: true
          name: "${spring.application.name}"
        # 서버가 Basic Auth면 아래 추가
        username: admin
        password: admin1234

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,threaddump,heapdump
  endpoint:
    health:
      show-details: always