apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: sample-k8s
build:
  artifacts:
    - image: application-app-1
      context: .
      docker:
        dockerfile: application/app-1/Dockerfile
    - image: application-app-2
      context: .
      docker:
        dockerfile: application/app-2/Dockerfile
    - image: shared-server-api-gateway
      context: .
      docker:
        dockerfile: shared-server/api-gateway/Dockerfile
    - image: shared-server-discovery-server
      context: .
      docker:
        dockerfile: shared-server/discovery-server/Dockerfile
manifests:
  rawYaml:
    - k8s/api-gateway/*.yaml
    - k8s/app-1/*.yaml
    - k8s/app-2/*.yaml
    - k8s/discovery-server/*.yaml
portForward:
  - resourceType: service
    resourceName: application-app-1
    port: 10000
  - resourceType: service
    resourceName: application-app-2
    port: 11000
  - resourceType: service
    resourceName: shared-server-api-gateway
    port: 8080
  - resourceType: service
    resourceName: shared-server-discovery-server
    port: 8761
