# api-gateway/src/main/resources/application.yml
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true        # Eureka 등록 서비스 자동 라우팅
          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: product
              uri: lb://product-service
              predicates:
                - Path=/products/**
            - id: order
              uri: lb://order-service
              predicates:
                - Path=/orders/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG