server:
  port: 8081

spring:
  application:
    name: resource-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/demo}
  threads:
    virtual:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.security: INFO
    com.revy: DEBUG