plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'org.springframework.boot' version '2.1.6.RELEASE'
    id 'io.spring.dependency-management' version '1.0.6.RELEASE'
    id 'com.google.cloud.tools.jib' version '3.5.3'
}

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
}

jib{
    to {
        // 원격 주소 대신 로컬에서 직관적으로 알아볼 수 있는 이름을 입력합니다.
        to {
            image = 'local-app'        // 로컬에서 사용할 이미지 이름
            // tags = ['latest', '1.0.0'] // (선택) 추가하고 싶은 태그들
        }

    }
}