CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS orderdb;

CREATE USER IF NOT EXISTS 'auth'@'%' IDENTIFIED BY 'authpass';
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'userpass';
CREATE USER IF NOT EXISTS 'order'@'%' IDENTIFIED BY 'orderpass';

GRANT ALL PRIVILEGES ON authdb.* TO 'auth'@'%';
GRANT ALL PRIVILEGES ON userdb.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON orderdb.* TO 'order'@'%';

FLUSH PRIVILEGES;
