plugins {
    id "org.openapi.generator"
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$rootDir/src/main/resources/swagger/api.yml".toString()
    outputDir = "$buildDir/openapi".toString()
    apiPackage = "com.revy.app.web.api"
    modelPackage = "com.revy.app.service.api.dto"
    apiFilesConstrainedTo = [""]
    modelFilesConstrainedTo = [""]
    supportingFilesConstrainedTo = ["ApiUtil.java"]
    configOptions = [delegatePattern: "true", title: "jhipster-app", useSpringBoot3: "true"]
    validateSpec = true
    importMappings = [Problem:"org.springframework.http.ProblemDetail"]
}

sourceSets {
    main {
        java {
            srcDir(file("${project.buildDir.path}/openapi/src/main/java"))
        }
    }
}

compileJava.dependsOn("openApiGenerate")
