
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-app-1
  labels:
    app: application-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: application-app-1
  template:
    metadata:
      labels:
        app: application-app-1
    spec:
      containers:
      - name: application-app-1
        image: application-app-1
        envFrom:
          - configMapRef:
              name: app-1-config