import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import {
  RefineSnackbarProvider,
  useNotificationProvider,
} from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                <DevtoolsProvider>
                  <Refine
                    routerProvider={routerProvider}
                    dataProvider={dataProvider}
                    notificationProvider={useNotificationProvider}
                    authProvider={authProviderClient}
                    resources={[
                      {
                        name: "domain-user-group",
                        meta: {
                          label: "User",
                        },
                      },
                      {
                        name: "users",
                        list: "/domain/users",
                        create: "/domain/users/create",
                        edit: "/domain/users/edit/:id",
                        show: "/domain/users/show/:id",
                        meta: {
                          parent: "domain-user-group",
                          label: "Users",
                          canDelete: true,
                        },
                      },
                      {
                        name: "domain-system-group",
                        meta: {
                          label: "SYSTEM",
                        },
                      },
                      {
                        name: "admins",
                        list: "/domain/admins",
                        create: "/domain/admins/create",
                        edit: "/domain/admins/edit/:id",
                        show: "/domain/admins/show/:id",
                        meta: {
                          parent: "domain-system-group",
                          label: "Admins",
                          canDelete: true,
                        },
                      },
                      {
                        name: "roles",
                        list: "/domain/roles",
                        create: "/domain/roles/create",
                        edit: "/domain/roles/edit/:id",
                        show: "/domain/roles/show/:id",
                        meta: {
                          parent: "domain-system-group",
                          label: "Roles",
                          canDelete: true,
                        },
                      },
                      {
                        name: "permissions",
                        list: "/domain/permissions",
                        create: "/domain/permissions/create",
                        edit: "/domain/permissions/edit/:id",
                        show: "/domain/permissions/show/:id",
                        meta: {
                          parent: "domain-system-group",
                          label: "Permissions",
                          canDelete: true,
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: false,
                      warnWhenUnsavedChanges: true,
                      projectId: "lwPvIE-b5A9ar-fADVIS",
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
                </DevtoolsProvider>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
