-- =====================================================================
-- Retirement Pension System - Initial PostgreSQL Schema
-- Flyway migration: V1__init_pension_schema.sql
--
-- Combined from the design document's V1 ~ V12 migrations.
-- Target: PostgreSQL 18.x / Flyway 12.4.x
--
-- Notes:
--   * Flyway manages the migration transaction; no manual BEGIN/COMMIT.
--   * Hibernate should run with ddl-auto=validate.
--   * Runtime application role should not have DDL privileges in production.
-- =====================================================================

-- =====================================================================
-- Original migration 01: V1__create_contract.sql
-- =====================================================================
create table employer (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    business_no varchar(20) not null,
    display_name varchar(200) not null,
    created_at timestamptz not null,
    constraint uk_employer_public_id unique(public_id),
    constraint uk_employer_business_no unique(business_no)
);

create table participant (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    profile_ref varchar(100) not null,
    status varchar(20) not null,
    created_at timestamptz not null,
    constraint uk_participant_public_id unique(public_id),
    constraint uk_participant_profile_ref unique(profile_ref)
);

create table plan_contract (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    contract_no varchar(80) not null,
    employer_id bigint references employer(id),
    plan_type varchar(10) not null,
    status varchar(20) not null,
    effective_at timestamptz not null,
    constraint uk_plan_contract_public_id unique(public_id),
    constraint uk_plan_contract_no unique(contract_no),
    constraint ck_plan_type check(plan_type in ('DB','DC','IRP'))
);
create index idx_contract_employer on plan_contract(employer_id);

-- =====================================================================
-- Original migration 02: V2__create_account.sql
-- =====================================================================
create table pension_account (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    contract_id bigint not null references plan_contract(id),
    participant_id bigint not null references participant(id),
    status varchar(30) not null,
    cash_balance numeric(19,2) not null default 0,
    reserved_cash numeric(19,2) not null default 0,
    version bigint not null default 0,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_pension_account_public_id unique(public_id),
    constraint uk_pension_account_contract_participant unique(contract_id, participant_id),
    constraint ck_account_cash_nonnegative check(cash_balance >= 0),
    constraint ck_account_reserved_nonnegative check(reserved_cash >= 0),
    constraint ck_account_reserved_lte_cash check(cash_balance >= reserved_cash)
);
create index idx_account_contract on pension_account(contract_id);
create index idx_account_participant on pension_account(participant_id);

-- =====================================================================
-- Original migration 03: V3__create_contribution.sql
-- =====================================================================
create table contribution (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    external_reference varchar(100) not null,
    amount numeric(19,2) not null,
    status varchar(30) not null,
    received_at timestamptz not null,
    version bigint not null default 0,
    constraint uk_contribution_external_reference unique(external_reference),
    constraint ck_contribution_amount_positive check(amount > 0)
);
create index idx_contribution_account_created on contribution(account_id, received_at desc);
create index idx_contribution_account_status on contribution(account_id, status);

-- =====================================================================
-- Original migration 04: V4__create_investment.sql
-- =====================================================================
create table product (
    id bigint generated by default as identity primary key,
    product_code varchar(50) not null,
    display_name varchar(200) not null,
    purchasable boolean not null,
    created_at timestamptz not null,
    constraint uk_product_code unique(product_code)
);

create table investment_instruction (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    version bigint not null default 0,
    constraint uk_instruction_account unique(account_id)
);

create table investment_allocation (
    id bigint generated by default as identity primary key,
    instruction_id bigint not null references investment_instruction(id),
    product_code varchar(50) not null references product(product_code),
    ratio numeric(7,4) not null,
    constraint uk_allocation_instruction_product unique(instruction_id, product_code),
    constraint ck_allocation_ratio check(ratio > 0 and ratio <= 100.0000)
);

-- =====================================================================
-- Original migration 05: V5__create_order.sql
-- =====================================================================
create table investment_order (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    client_order_id varchar(100) not null,
    product_code varchar(50) not null references product(product_code),
    side varchar(10) not null,
    requested_amount numeric(19,2) not null,
    filled_amount numeric(19,2) not null default 0,
    status varchar(30) not null,
    version bigint not null default 0,
    created_at timestamptz not null,
    constraint uk_order_client_order_id unique(client_order_id),
    constraint ck_order_requested_positive check(requested_amount > 0),
    constraint ck_order_filled_nonnegative check(filled_amount >= 0),
    constraint ck_order_filled_lte_requested check(filled_amount <= requested_amount)
);
create index idx_order_account_created on investment_order(account_id, created_at desc);
create index idx_order_account_status on investment_order(account_id, status);
create index idx_order_status_created on investment_order(status, created_at);

create table order_execution (
    id bigint generated by default as identity primary key,
    order_id bigint not null references investment_order(id),
    external_execution_id varchar(100) not null,
    executed_amount numeric(19,2) not null,
    quantity numeric(24,8) not null,
    executed_at timestamptz not null,
    constraint uk_execution_external_execution_id unique(external_execution_id),
    constraint ck_execution_amount_positive check(executed_amount > 0),
    constraint ck_execution_quantity_positive check(quantity > 0)
);
create index idx_execution_order_time on order_execution(order_id, executed_at);

-- =====================================================================
-- Original migration 06: V6__create_holding.sql
-- =====================================================================
create table holding (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    product_code varchar(50) not null references product(product_code),
    quantity numeric(24,8) not null,
    book_value numeric(19,2) not null,
    market_value numeric(19,2) not null,
    valuation_date date,
    version bigint not null default 0,
    constraint uk_holding_account_product unique(account_id, product_code),
    constraint ck_holding_quantity_nonnegative check(quantity >= 0),
    constraint ck_holding_book_nonnegative check(book_value >= 0),
    constraint ck_holding_market_nonnegative check(market_value >= 0)
);
create index idx_holding_account on holding(account_id);

-- =====================================================================
-- Original migration 07: V7__create_ledger.sql
-- =====================================================================
create table ledger_entry (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    transaction_id uuid not null,
    sequence integer not null,
    event_type varchar(50) not null,
    product_code varchar(50),
    cash_delta numeric(19,2) not null,
    quantity_delta numeric(24,8) not null,
    occurred_at timestamptz not null,
    created_at timestamptz not null,
    constraint uk_ledger_transaction_sequence unique(transaction_id, sequence),
    constraint ck_ledger_sequence_positive check(sequence > 0)
);
create index idx_ledger_account_created on ledger_entry(account_id, created_at desc);
create index idx_ledger_account_product on ledger_entry(account_id, product_code, created_at desc) where product_code is not null;

-- =====================================================================
-- Original migration 08: V8__create_benefit.sql
-- =====================================================================
create table benefit_claim (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    requested_amount numeric(19,2) not null,
    reason_code varchar(50) not null,
    status varchar(30) not null,
    rejection_reason_code varchar(50),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    version bigint not null default 0,
    constraint ck_benefit_amount_positive check(requested_amount > 0)
);
create index idx_benefit_account_created on benefit_claim(account_id, created_at desc);
create index idx_benefit_status_created on benefit_claim(status, created_at);

create table tax_result (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references benefit_claim(id),
    policy_version varchar(50) not null,
    taxable_amount numeric(19,2) not null,
    tax_amount numeric(19,2) not null,
    calculated_at timestamptz not null,
    constraint ck_taxable_nonnegative check(taxable_amount >= 0),
    constraint ck_tax_nonnegative check(tax_amount >= 0)
);

create table payment_execution (
    id bigint generated by default as identity primary key,
    claim_id bigint not null references benefit_claim(id),
    external_payment_id varchar(100) not null,
    amount numeric(19,2) not null,
    paid_at timestamptz not null,
    constraint uk_payment_external_id unique(external_payment_id),
    constraint ck_payment_amount_positive check(amount > 0)
);

-- =====================================================================
-- Original migration 09: V9__create_transfer.sql
-- =====================================================================
create table account_transfer (
    id bigint generated by default as identity primary key,
    public_id uuid not null,
    source_account_id bigint not null references pension_account(id),
    target_account_id bigint references pension_account(id),
    external_target_reference varchar(150),
    amount numeric(19,2) not null,
    status varchar(30) not null,
    failure_code varchar(50),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    version bigint not null default 0,
    constraint uk_transfer_public_id unique(public_id),
    constraint ck_transfer_amount_positive check(amount > 0),
    constraint ck_transfer_one_target check(
        (target_account_id is not null and external_target_reference is null)
        or (target_account_id is null and external_target_reference is not null)
    ),
    constraint ck_transfer_different_accounts check(target_account_id is null or target_account_id <> source_account_id)
);
create index idx_transfer_source_created on account_transfer(source_account_id, created_at desc);
create index idx_transfer_status_created on account_transfer(status, created_at);

-- =====================================================================
-- Original migration 10: V10__create_outbox.sql
-- =====================================================================
create table outbox_event (
    id uuid primary key,
    aggregate_type varchar(50) not null,
    aggregate_id varchar(100) not null,
    event_type varchar(100) not null,
    payload jsonb not null,
    occurred_at timestamptz not null,
    created_at timestamptz not null,
    status varchar(20) not null,
    next_attempt_at timestamptz not null,
    claimed_at timestamptz,
    published_at timestamptz,
    retry_count integer not null default 0,
    constraint ck_outbox_retry_nonnegative check(retry_count >= 0)
);
create index idx_outbox_ready on outbox_event(next_attempt_at, created_at) where status in ('PENDING','FAILED');
create index idx_outbox_processing on outbox_event(claimed_at) where status = 'PROCESSING';

-- =====================================================================
-- Original migration 11: V11__create_idempotency.sql
-- =====================================================================
create table idempotency_record (
    id bigint generated by default as identity primary key,
    operation varchar(80) not null,
    idempotency_key varchar(200) not null,
    request_hash varchar(64) not null,
    status varchar(20) not null,
    response_status integer,
    response_body text,
    resource_id varchar(100),
    created_at timestamptz not null,
    updated_at timestamptz not null,
    constraint uk_idempotency_operation_key unique(operation, idempotency_key),
    constraint ck_idempotency_response_status check(response_status is null or response_status between 100 and 599)
);
create index idx_idempotency_created on idempotency_record(created_at);

-- =====================================================================
-- Original migration 12: V12__create_db_plan_audit_support.sql
-- =====================================================================
create table plan_asset_pool (
    id bigint generated by default as identity primary key,
    contract_id bigint not null references plan_contract(id),
    asset_value numeric(19,2) not null,
    valuation_date date,
    version bigint not null default 0,
    constraint uk_asset_pool_contract unique(contract_id),
    constraint ck_asset_pool_nonnegative check(asset_value >= 0)
);

create table plan_liability (
    id bigint generated by default as identity primary key,
    contract_id bigint not null references plan_contract(id),
    liability_amount numeric(19,2) not null,
    valuation_date date not null,
    created_at timestamptz not null,
    constraint uk_liability_contract_date unique(contract_id, valuation_date),
    constraint ck_liability_nonnegative check(liability_amount >= 0)
);

create table benefit_entitlement (
    id bigint generated by default as identity primary key,
    contract_id bigint not null references plan_contract(id),
    participant_id bigint not null references participant(id),
    entitled_amount numeric(19,2) not null,
    calculated_at timestamptz not null,
    version bigint not null default 0,
    constraint uk_entitlement_contract_participant unique(contract_id, participant_id),
    constraint ck_entitlement_nonnegative check(entitled_amount >= 0)
);

create table audit_log (
    id uuid primary key,
    trace_id varchar(64) not null,
    actor_type varchar(30) not null,
    actor_id varchar(100),
    action varchar(100) not null,
    aggregate_type varchar(60) not null,
    aggregate_id varchar(100) not null,
    channel varchar(30) not null,
    source_ip varchar(64),
    occurred_at timestamptz not null
);
create index idx_audit_aggregate on audit_log(aggregate_type, aggregate_id, occurred_at desc);
create index idx_audit_trace on audit_log(trace_id);

create table fee (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    fee_type varchar(40) not null,
    amount numeric(19,2) not null,
    occurred_at timestamptz not null,
    constraint ck_fee_nonnegative check(amount >= 0)
);

create table retirement_event (
    id uuid primary key,
    participant_id bigint not null references participant(id),
    retirement_date date not null,
    event_type varchar(40) not null,
    recorded_at timestamptz not null
);

create table daily_valuation (
    id bigint generated by default as identity primary key,
    account_id bigint not null references pension_account(id),
    product_code varchar(50) not null references product(product_code),
    valuation_date date not null,
    quantity numeric(24,8) not null,
    market_value numeric(19,2) not null,
    constraint uk_daily_valuation unique(account_id, product_code, valuation_date),
    constraint ck_daily_quantity_nonnegative check(quantity >= 0),
    constraint ck_daily_market_nonnegative check(market_value >= 0)
);
