
pluginManagement {
    repositories {
        // jhipster-needle-gradle-plugin-management-repositories - JHipster will add additional entries here
    }
    buildscript {
        repositories {
            mavenCentral()
        }
        dependencies {
            classpath "org.liquibase:liquibase-core:${liquibaseVersion}"
        }
    }
    plugins {
        id "com.gradle.develocity" version "${gradleDevelocityPluginVersion}"
        id "com.gradle.common-custom-user-data-gradle-plugin" version "${gradleCommonCustomUserDataPluginVersion}"
        id "org.liquibase.gradle" version "${liquibasePluginVersion}"
        // jhipster-needle-gradle-plugin-management-plugins - JHipster will add additional entries here
    }
}

plugins {
    id 'com.gradle.develocity'
    id 'com.gradle.common-custom-user-data-gradle-plugin'
}

develocity {
    server = "none"
    buildScan {
        captureTaskInputFiles = true
        uploadInBackground = System.getenv("CI") == null // adjust to your CI provider
        publishAlways()
    }
}

buildCache {
    local { enabled = true }
    remote(HttpBuildCache) {
        push = true
        enabled = false // Disabled as this might not always desired
        url = 'none/cache/' // note the trailing slash!
    }
}
rootProject.name = "jhipster-app"
