org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8

### 의존성 버전 정보
springBootVersion=4.1.0
dependencyManagementVersion=1.1.7
jibVersion=3.5.3
springCloudVersion=2025.1.2
opentelemetryVersion=2.28.1


# 공통 Jib 기반 이미지
jibBaseImage=eclipse-temurin:21-jre-alpine
