services:
  postgres:
    image: postgres:16-alpine
    container_name: example-db
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - example-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql -d postgresql"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: example-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: example-redis-commander
    environment:
      REDIS_HOSTS: >
        db0:redis:6379:0,
        db1:redis:6379:1
    ports:
      - "16379:8081"
    depends_on:
      - redis

volumes:
  example-data:
  redis-data:

