spring:
  application:
    name: sample-data-source
  profiles:
    default: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false

logging:
  level:
    com.revy.*: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace