spring:
  application:
    name: my-app

  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: myapp
    password: myapp1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: validate   # 운영: validate / none, 로컬: update (개발 초기에만)
      ddl-auto: update
    open-in-view: false    # 실무에서는 false 권장 (OSIV 비활성화)
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: false

  docker:
    compose:
      enabled: true
#      file: ./docker-compose.yml
      lifecycle-management: start_and_stop

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.boot.docker.compose: trace
