rootProject.name = 'backend'

// module
include ':module:core:common'
include ':module:core:core-exception'
include ':module:core:core-web'
include ':module:core:core-domain'
include ':module:domain'
include ':module:business-logic'
include ':module:jwt-auth'
include ':module:tools:log-elk'
include ':module:tools:metrics'

// application-server
include ':application:api-admin'
include ':application:api-saas'
