server:
  port: 9002

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mariadb://mariadb:3306/orderdb
    username: order
    password: orderpass
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

springdoc:
  show-actuator: true