server:
  port: 8081

spring:
  application:
    name: outbox-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: UTC

    kafka:
      bootstrap-servers: localhost:9092

      consumer:
        group-id: outbox-demo-consumer
        auto-offset-reset: earliest
        enable-auto-commit: false
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

      listener:
        ack-mode: manual_immediate


logging:
  level:
    org.hibernate.SQL: debug