
/*
create table admin (
                       id bigserial primary key,
                       email varchar(255) not null unique,
                       password varchar(255) not null,
                       name varchar(100) not null,
                       role varchar(30) not null,
                       created_at timestamp(6) with time zone not null,
                       updated_at timestamp(6) with time zone not null
);
*/

CREATE TABLE admin
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    role       VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

ALTER TABLE admin
    ADD CONSTRAINT uc_admin_email UNIQUE (email);