CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title      VARCHAR(200)                            NOT NULL,
    content    TEXT                                    NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);