spring:
  application:
    name: api-admin
  profiles:
    active: ${APP_PROFILE:local}
    default: local
  config:
    import:
      - "optional:classpath:/metrics.yml"
      - "optional:classpath:/springdoc.yml"
      - "optional:classpath:/scheduler-quartz.properties"
  datasource:
    url: ${ADMIN_DB_URL:jdbc:postgresql://localhost:5431/appdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
#      password: ${REDIS_PASSWORD:mypassword}
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
  batch:
    job:
      enabled: false             # api-admin 은 launch 안 함 (워커 노드 전담)
    jdbc:
      initialize-schema: never

  #virtual thread
  threads:
    virtual:
      enabled: true


server:
  port: ${ADMIN_SERVER_PORT:8081}

app:
  jwt:
    issuer: ${JWT_ISSUER:api-admin}
    secret: ${JWT_SECRET:a8cc92c8b53c71c7904a1266bd6d5dadb0033eab4c8e9ee3307dae77ffe26010c7cadfcde4c7e4ab1890a8301ebbf7714ffc7e545250d46a06aae9bff52d0d50}
    access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:60}
    refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:14}

logging:
  level:
    org.hibernate.SQL: debug

logstash:
  enabled: true
  host: ${LOGSTASH_HOST:127.0.0.1:4560}