server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/demo}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_GATEWAY_CLIENT_ID:gateway-client}
            client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET:gateway-secret-change-me}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/demo}
#            user-name-attribute: preferred_username
#
#        registration:
#          keycloak:
#            provider: keycloak
#            client-id: ${KEYCLOAK_GATEWAY_CLIENT_ID:gateway-client}
#
#            # 운영 환경에서는 기본값을 두지 않는 것이 안전함
#            client-secret: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
#
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - openid
#              - profile
#              - email

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: resource-service
              uri: ${RESOURCE_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/**
              filters:
                # 현재 로그인한 OAuth2 사용자의 access token 전달
                - TokenRelay=

management:
  endpoint:
    gateway:
      # Spring Cloud Gateway 5에서 gateway actuator는 기본 비활성화
      access: read-only

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG