-- ============================================================
--  FX 도메인 DDL
--  currency / exchange_rate / fx_conversion
-- ============================================================

-- public.currency definition
-- DROP TABLE public.currency;

CREATE TABLE public.currency (
    id           int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at   timestamptz(6) NOT NULL,
    updated_at   timestamptz(6) NOT NULL,
    code         varchar(3)   NOT NULL,
    "name"       varchar(100) NOT NULL,
    symbol       varchar(10)  NOT NULL,
    decimal_places int4       NOT NULL,
    is_active    bool         NOT NULL,
    CONSTRAINT currency_pkey      PRIMARY KEY (id),
    CONSTRAINT uq_currency_code   UNIQUE (code)
);
CREATE INDEX idx_currency_active ON public.currency USING btree (is_active);


-- public.exchange_rate definition
-- DROP TABLE public.exchange_rate;

CREATE TABLE public.exchange_rate (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6) NOT NULL,
    updated_at          timestamptz(6) NOT NULL,
    base_currency_code  varchar(3)   NOT NULL,
    quote_currency_code varchar(3)   NOT NULL,
    rate_type           varchar(20)  NOT NULL,
    rate                numeric(18, 8) NOT NULL,
    quoted_at           timestamptz(6) NOT NULL,
    source              varchar(50)  NOT NULL,
    CONSTRAINT exchange_rate_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_fx_pair_type_at ON public.exchange_rate USING btree (base_currency_code, quote_currency_code, rate_type, quoted_at);
CREATE INDEX idx_fx_quoted_at    ON public.exchange_rate USING btree (quoted_at);


-- public.fx_conversion definition
-- DROP TABLE public.fx_conversion;

CREATE TABLE public.fx_conversion (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6) NOT NULL,
    updated_at          timestamptz(6) NOT NULL,
    "version"           int8         NOT NULL,
    conversion_number   varchar(30)  NOT NULL,
    from_account_id     int8         NOT NULL,
    to_account_id       int8         NOT NULL,
    from_currency_code  varchar(3)   NOT NULL,
    to_currency_code    varchar(3)   NOT NULL,
    from_amount         numeric(20, 4) NOT NULL,
    to_amount           numeric(20, 4) NOT NULL,
    applied_rate        numeric(18, 8) NOT NULL,
    applied_rate_type   varchar(20)  NOT NULL,
    fee                 numeric(18, 4) NOT NULL,
    status              varchar(20)  NOT NULL,
    debit_tx_id         int8         NULL,
    credit_tx_id        int8         NULL,
    executed_at         timestamptz(6) NULL,
    failure_reason      varchar(200) NULL,
    reference_id        varchar(64)  NOT NULL,
    CONSTRAINT fx_conversion_pkey       PRIMARY KEY (id),
    CONSTRAINT uq_fx_conversion_number  UNIQUE (conversion_number),
    CONSTRAINT uq_fx_reference_id       UNIQUE (reference_id)
);
CREATE INDEX idx_fx_from_account ON public.fx_conversion USING btree (from_account_id);
CREATE INDEX idx_fx_to_account   ON public.fx_conversion USING btree (to_account_id);
CREATE INDEX idx_fx_executed_at  ON public.fx_conversion USING btree (executed_at);
CREATE INDEX idx_fx_status       ON public.fx_conversion USING btree (status);
