-- =====================================================================
-- RBAC: admin_role / admin_role_permission / admin_roles
-- =====================================================================

CREATE TABLE admin_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_admin_role        PRIMARY KEY (id),
    CONSTRAINT uq_admin_role_name   UNIQUE (name)
);

-- @ElementCollection 매핑 (역할이 보유한 권한 enum 집합)
CREATE TABLE admin_role_permission
(
    role_id    BIGINT      NOT NULL,
    permission VARCHAR(50) NOT NULL,
    CONSTRAINT pk_admin_role_permission PRIMARY KEY (role_id, permission),
    CONSTRAINT fk_arp_role               FOREIGN KEY (role_id)
        REFERENCES admin_role (id) ON DELETE CASCADE
);
CREATE INDEX idx_admin_role_permission_role ON admin_role_permission (role_id);

-- Admin ↔ AdminRole 다대다 조인
CREATE TABLE admin_roles
(
    admin_id BIGINT NOT NULL,
    role_id  BIGINT NOT NULL,
    CONSTRAINT pk_admin_roles    PRIMARY KEY (admin_id, role_id),
    CONSTRAINT fk_admin_roles_a  FOREIGN KEY (admin_id) REFERENCES admin (id)      ON DELETE CASCADE,
    CONSTRAINT fk_admin_roles_r  FOREIGN KEY (role_id)  REFERENCES admin_role (id) ON DELETE CASCADE
);
CREATE INDEX idx_admin_roles_admin ON admin_roles (admin_id);
CREATE INDEX idx_admin_roles_role  ON admin_roles (role_id);

-- =====================================================================
-- 기본 역할 데이터
-- =====================================================================

INSERT INTO admin_role (created_at, updated_at, name, description) VALUES
    (now(), now(), 'SUPER_ADMIN',         '전체 권한을 가진 슈퍼 어드민'),
    (now(), now(), 'ACCOUNT_MANAGER',     '계좌·이체·거래내역 관리 담당자'),
    (now(), now(), 'STOCK_TRADER',        '주식 종목·주문·체결 관리 담당자'),
    (now(), now(), 'FX_OPERATOR',         '외환 통화·환율·환전 관리 담당자'),
    (now(), now(), 'INSURANCE_REVIEWER',  '보험 상품·증권·청구 심사 담당자'),
    (now(), now(), 'LEDGER_ACCOUNTANT',   '원장(분개·시산표) 담당 회계 담당자'),
    (now(), now(), 'SCHEDULER_OPERATOR',  'Quartz / Batch 운영 담당자'),
    (now(), now(), 'AUDITOR',             '전 영역 읽기 전용 감사 담당자');

-- =====================================================================
-- 역할별 권한 매핑
-- =====================================================================

-- SUPER_ADMIN → 모든 권한
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('USER_READ'),('USER_WRITE'),
    ('ACCOUNT_READ'),('ACCOUNT_WRITE'),('ACCOUNT_TRANSFER'),
    ('STOCK_READ'),('STOCK_WRITE'),
    ('ORDER_READ'),('ORDER_WRITE'),('ORDER_EXECUTE'),('ORDER_CANCEL'),
    ('TRADE_READ'),
    ('FX_READ'),('FX_WRITE'),('FX_CONVERT'),
    ('INSURANCE_READ'),('INSURANCE_WRITE'),('INSURANCE_CLAIM'),
    ('LEDGER_READ'),('LEDGER_WRITE'),
    ('ADMIN_READ'),('ADMIN_WRITE'),
    ('ROLE_READ'),('ROLE_WRITE'),
    ('SCHEDULER_READ'),('SCHEDULER_WRITE')
) AS p(permission)
WHERE r.name = 'SUPER_ADMIN';

-- ACCOUNT_MANAGER → 사용자 읽기 + 계좌 전체 + 거래내역(이체 트랜잭션 보기)
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('USER_READ'),
    ('ACCOUNT_READ'),('ACCOUNT_WRITE'),('ACCOUNT_TRANSFER'),
    ('FX_READ'),('FX_CONVERT')
) AS p(permission)
WHERE r.name = 'ACCOUNT_MANAGER';

-- STOCK_TRADER → 주식·주문·체결 관리
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('USER_READ'),
    ('ACCOUNT_READ'),
    ('STOCK_READ'),('STOCK_WRITE'),
    ('ORDER_READ'),('ORDER_WRITE'),('ORDER_EXECUTE'),('ORDER_CANCEL'),
    ('TRADE_READ')
) AS p(permission)
WHERE r.name = 'STOCK_TRADER';

-- FX_OPERATOR → 외환 통화·환율·환전 운영
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('USER_READ'),
    ('ACCOUNT_READ'),
    ('FX_READ'),('FX_WRITE'),('FX_CONVERT')
) AS p(permission)
WHERE r.name = 'FX_OPERATOR';

-- INSURANCE_REVIEWER → 보험 심사
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('USER_READ'),
    ('ACCOUNT_READ'),
    ('INSURANCE_READ'),('INSURANCE_WRITE'),('INSURANCE_CLAIM')
) AS p(permission)
WHERE r.name = 'INSURANCE_REVIEWER';

-- LEDGER_ACCOUNTANT → 원장 관리
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('LEDGER_READ'),('LEDGER_WRITE'),
    ('ACCOUNT_READ'),
    ('TRADE_READ')
) AS p(permission)
WHERE r.name = 'LEDGER_ACCOUNTANT';

-- SCHEDULER_OPERATOR → Quartz / Batch
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('SCHEDULER_READ'),('SCHEDULER_WRITE')
) AS p(permission)
WHERE r.name = 'SCHEDULER_OPERATOR';

-- AUDITOR → 전 영역 READ 만
INSERT INTO admin_role_permission (role_id, permission)
SELECT r.id, p.permission
FROM admin_role r
CROSS JOIN (VALUES
    ('USER_READ'),
    ('ACCOUNT_READ'),
    ('STOCK_READ'),
    ('ORDER_READ'),
    ('TRADE_READ'),
    ('FX_READ'),
    ('INSURANCE_READ'),
    ('LEDGER_READ'),
    ('ADMIN_READ'),
    ('ROLE_READ'),
    ('SCHEDULER_READ')
) AS p(permission)
WHERE r.name = 'AUDITOR';

-- =====================================================================
-- 데모 어드민 → SUPER_ADMIN 역할 자동 할당
-- (V20260519160000 마이그레이션이 생성한 admin01..admin05@example.com)
-- =====================================================================

INSERT INTO admin_roles (admin_id, role_id)
SELECT a.id, r.id
FROM admin a, admin_role r
WHERE a.email LIKE 'admin%@example.com'
  AND r.name = 'SUPER_ADMIN'
  AND NOT EXISTS (
      SELECT 1 FROM admin_roles ar
      WHERE ar.admin_id = a.id AND ar.role_id = r.id
  );
