-- =====================================================================
-- stock_order — 주식 주문
-- =====================================================================

CREATE TABLE stock_order
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    version         BIGINT                                  NOT NULL,
    account_id      BIGINT                                  NOT NULL,
    stock_id        BIGINT                                  NOT NULL,
    side            VARCHAR(10)                             NOT NULL,
    order_type      VARCHAR(10)                             NOT NULL,
    quantity        NUMERIC(20, 8)                          NOT NULL,
    limit_price     NUMERIC(20, 4),
    filled_quantity NUMERIC(20, 8)                          NOT NULL,
    avg_fill_price  NUMERIC(20, 4),
    status          VARCHAR(20)                             NOT NULL,
    reference_id    VARCHAR(64)                             NOT NULL,
    ordered_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    filled_at       TIMESTAMP WITHOUT TIME ZONE,
    cancelled_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stock_order                  PRIMARY KEY (id),
    CONSTRAINT uq_stock_order_reference_id     UNIQUE (reference_id)
);

CREATE INDEX idx_stock_order_account_id ON stock_order (account_id);
CREATE INDEX idx_stock_order_stock_id   ON stock_order (stock_id);
CREATE INDEX idx_stock_order_status     ON stock_order (status);
CREATE INDEX idx_stock_order_ordered_at ON stock_order (ordered_at);

-- =====================================================================
-- 기초 데이터 — 데모 계좌 × 종목 조합으로 다양한 상태의 주문 5건
--   1) FILLED  매수 시장가
--   2) FILLED  매도 지정가
--   3) PENDING 매수 지정가
--   4) CANCELLED 매수 시장가
--   5) FILLED  매수 지정가
-- =====================================================================

INSERT INTO stock_order (
    created_at, updated_at, version, account_id, stock_id, side, order_type,
    quantity, limit_price, filled_quantity, avg_fill_price, status, reference_id,
    ordered_at, filled_at, cancelled_at
)
SELECT
    now() - interval '5 days', now() - interval '5 days', 0,
    (SELECT id FROM account WHERE account_number IS NOT NULL ORDER BY id LIMIT 1),
    (SELECT id FROM stock ORDER BY id LIMIT 1),
    'BUY', 'MARKET',
    10,        NULL,
    10,        75000.0000,
    'FILLED',  'demo-ord-001',
    now() - interval '5 days',
    now() - interval '5 days' + interval '3 seconds',
    NULL
WHERE EXISTS (SELECT 1 FROM account) AND EXISTS (SELECT 1 FROM stock)
  AND NOT EXISTS (SELECT 1 FROM stock_order WHERE reference_id = 'demo-ord-001');

INSERT INTO stock_order (
    created_at, updated_at, version, account_id, stock_id, side, order_type,
    quantity, limit_price, filled_quantity, avg_fill_price, status, reference_id,
    ordered_at, filled_at, cancelled_at
)
SELECT
    now() - interval '3 days', now() - interval '3 days', 0,
    (SELECT id FROM account ORDER BY id LIMIT 1),
    (SELECT id FROM stock ORDER BY id LIMIT 1),
    'SELL', 'LIMIT',
    5,         80000.0000,
    5,         80000.0000,
    'FILLED',  'demo-ord-002',
    now() - interval '3 days',
    now() - interval '3 days' + interval '15 minutes',
    NULL
WHERE EXISTS (SELECT 1 FROM account) AND EXISTS (SELECT 1 FROM stock)
  AND NOT EXISTS (SELECT 1 FROM stock_order WHERE reference_id = 'demo-ord-002');

INSERT INTO stock_order (
    created_at, updated_at, version, account_id, stock_id, side, order_type,
    quantity, limit_price, filled_quantity, avg_fill_price, status, reference_id,
    ordered_at, filled_at, cancelled_at
)
SELECT
    now() - interval '6 hours', now() - interval '6 hours', 0,
    (SELECT id FROM account ORDER BY id LIMIT 1 OFFSET 1),
    (SELECT id FROM stock ORDER BY id LIMIT 1 OFFSET 1),
    'BUY', 'LIMIT',
    20,        72000.0000,
    0,         NULL,
    'PENDING', 'demo-ord-003',
    now() - interval '6 hours',
    NULL, NULL
WHERE (SELECT COUNT(*) FROM account) >= 2 AND (SELECT COUNT(*) FROM stock) >= 2
  AND NOT EXISTS (SELECT 1 FROM stock_order WHERE reference_id = 'demo-ord-003');

INSERT INTO stock_order (
    created_at, updated_at, version, account_id, stock_id, side, order_type,
    quantity, limit_price, filled_quantity, avg_fill_price, status, reference_id,
    ordered_at, filled_at, cancelled_at
)
SELECT
    now() - interval '2 days', now() - interval '2 days', 0,
    (SELECT id FROM account ORDER BY id LIMIT 1),
    (SELECT id FROM stock ORDER BY id LIMIT 1),
    'BUY', 'MARKET',
    8,         NULL,
    0,         NULL,
    'CANCELLED', 'demo-ord-004',
    now() - interval '2 days',
    NULL,
    now() - interval '2 days' + interval '5 minutes'
WHERE EXISTS (SELECT 1 FROM account) AND EXISTS (SELECT 1 FROM stock)
  AND NOT EXISTS (SELECT 1 FROM stock_order WHERE reference_id = 'demo-ord-004');

INSERT INTO stock_order (
    created_at, updated_at, version, account_id, stock_id, side, order_type,
    quantity, limit_price, filled_quantity, avg_fill_price, status, reference_id,
    ordered_at, filled_at, cancelled_at
)
SELECT
    now() - interval '12 hours', now() - interval '12 hours', 0,
    (SELECT id FROM account ORDER BY id LIMIT 1),
    (SELECT id FROM stock ORDER BY id LIMIT 1 OFFSET 1),
    'BUY', 'LIMIT',
    15,        45000.0000,
    15,        45000.0000,
    'FILLED',  'demo-ord-005',
    now() - interval '12 hours',
    now() - interval '12 hours' + interval '1 hour',
    NULL
WHERE EXISTS (SELECT 1 FROM account) AND (SELECT COUNT(*) FROM stock) >= 2
  AND NOT EXISTS (SELECT 1 FROM stock_order WHERE reference_id = 'demo-ord-005');
