-- =====================================================================
-- billing_item — 청구서 항목 (BillingInvoice 애그리거트의 child)
-- =====================================================================

CREATE TABLE billing_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    invoice_id  BIGINT                                  NOT NULL,
    type        VARCHAR(30)                             NOT NULL, -- ACCOUNT_FEE / TRADE_COMMISSION / FX_SPREAD_FEE / TRANSFER_FEE / INSURANCE_PREMIUM / SERVICE_FEE
    description VARCHAR(200)                            NOT NULL,
    quantity    NUMERIC(10, 4)                          NOT NULL,
    unit_price  NUMERIC(20, 4)                          NOT NULL,
    amount      NUMERIC(20, 4)                          NOT NULL,
    CONSTRAINT pk_billing_item       PRIMARY KEY (id),
    CONSTRAINT fk_billing_item_inv   FOREIGN KEY (invoice_id)
        REFERENCES billing_invoice (id) ON DELETE CASCADE
);

CREATE INDEX idx_billing_item_invoice_id ON billing_item (invoice_id);

-- =====================================================================
-- 기초 데이터 — V20260522130100 의 PAID/ISSUED 청구서에 항목 채우기
-- =====================================================================

-- 청구서 #1 (PAID, 50000원 소계) — 2개 항목
INSERT INTO billing_item (
    created_at, updated_at, invoice_id, type, description, quantity, unit_price, amount
)
SELECT now(), now(), inv.id, 'ACCOUNT_FEE',     '월 계좌 유지 수수료', 1, 30000, 30000
FROM billing_invoice inv
WHERE inv.note = '데모 청구서 #1 (납부 완료)';

INSERT INTO billing_item (
    created_at, updated_at, invoice_id, type, description, quantity, unit_price, amount
)
SELECT now(), now(), inv.id, 'TRADE_COMMISSION','주식 체결 수수료 (10건)', 10, 2000, 20000
FROM billing_invoice inv
WHERE inv.note = '데모 청구서 #1 (납부 완료)';

-- 청구서 #2 (ISSUED, 80000원 소계) — 3개 항목
INSERT INTO billing_item (
    created_at, updated_at, invoice_id, type, description, quantity, unit_price, amount
)
SELECT now(), now(), inv.id, 'ACCOUNT_FEE',     '월 계좌 유지 수수료', 1, 30000, 30000
FROM billing_invoice inv
WHERE inv.note = '데모 청구서 #2 (발행, 납부 대기)';

INSERT INTO billing_item (
    created_at, updated_at, invoice_id, type, description, quantity, unit_price, amount
)
SELECT now(), now(), inv.id, 'TRADE_COMMISSION','주식 체결 수수료 (15건)', 15, 2000, 30000
FROM billing_invoice inv
WHERE inv.note = '데모 청구서 #2 (발행, 납부 대기)';

INSERT INTO billing_item (
    created_at, updated_at, invoice_id, type, description, quantity, unit_price, amount
)
SELECT now(), now(), inv.id, 'FX_SPREAD_FEE',   '환전 스프레드 수수료',   2, 10000, 20000
FROM billing_invoice inv
WHERE inv.note = '데모 청구서 #2 (발행, 납부 대기)';
