-- ============================================================
--  PG (Payment Gateway) 도메인 DDL
--    pg_merchant  / pg_payment  / pg_settlement
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- pg_merchant — PG 가맹점
-- ─────────────────────────────────────────────────────────────
-- 가맹점별 수수료율(commission_rate)과 정산 주기(settlement_cycle)를 관리.
-- 정산 배치가 settlement_cycle 일 전 승인 결제를 집계해 pg_settlement 를 생성한다.

CREATE TABLE pg_merchant
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMPTZ(6)                          NOT NULL,
    updated_at            TIMESTAMPTZ(6)                          NOT NULL,
    merchant_code         VARCHAR(30)                             NOT NULL,
    name                  VARCHAR(200)                            NOT NULL,
    business_type         VARCHAR(50)                             NOT NULL,
    settlement_account_id BIGINT                                  NOT NULL,
    commission_rate       NUMERIC(6, 4)                           NOT NULL, -- 예: 0.0300 = 3%
    settlement_cycle      INT                                     NOT NULL DEFAULT 2, -- T+n 일
    currency              VARCHAR(3)                              NOT NULL DEFAULT 'KRW',
    is_active             BOOLEAN                                 NOT NULL DEFAULT TRUE,
    contact_email         VARCHAR(200),
    CONSTRAINT pk_pg_merchant         PRIMARY KEY (id),
    CONSTRAINT uq_pg_merchant_code    UNIQUE (merchant_code)
);

CREATE INDEX idx_pg_merchant_active   ON pg_merchant (is_active);
CREATE INDEX idx_pg_merchant_biz_type ON pg_merchant (business_type);


-- ─────────────────────────────────────────────────────────────
-- pg_payment — PG 결제
-- ─────────────────────────────────────────────────────────────
-- 상태 흐름: REQUESTED → APPROVED | FAILED
--            APPROVED  → CANCELLED | REFUNDED
-- 정산 배치 처리 후 pg_settlement_id 가 설정된다.

CREATE TABLE pg_payment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMPTZ(6)                          NOT NULL,
    updated_at        TIMESTAMPTZ(6)                          NOT NULL,
    merchant_id       BIGINT                                  NOT NULL,
    payment_method    VARCHAR(30)                             NOT NULL, -- CARD / BANK_TRANSFER / KAKAO_PAY / NAVER_PAY / TOSS_PAY / VIRTUAL_ACCOUNT
    order_no          VARCHAR(64)                             NOT NULL, -- 가맹점 발행 주문번호 (멱등성 키)
    amount            NUMERIC(20, 2)                          NOT NULL,
    commission_amount NUMERIC(20, 2)                          NOT NULL, -- amount × commission_rate
    net_amount        NUMERIC(20, 2)                          NOT NULL, -- amount − commission_amount
    currency          VARCHAR(3)                              NOT NULL DEFAULT 'KRW',
    status            VARCHAR(20)                             NOT NULL, -- REQUESTED / APPROVED / CANCELLED / REFUNDED / FAILED
    requested_at      TIMESTAMPTZ(6)                          NOT NULL,
    approved_at       TIMESTAMPTZ(6),
    cancelled_at      TIMESTAMPTZ(6),
    pg_settlement_id  BIGINT,                                           -- 정산 배치 후 연결
    CONSTRAINT pk_pg_payment          PRIMARY KEY (id),
    CONSTRAINT uq_pg_payment_order_no UNIQUE (order_no)
);

CREATE INDEX idx_pg_payment_merchant_id   ON pg_payment (merchant_id);
CREATE INDEX idx_pg_payment_status        ON pg_payment (status);
CREATE INDEX idx_pg_payment_approved_at   ON pg_payment (approved_at);
CREATE INDEX idx_pg_payment_settlement_id ON pg_payment (pg_settlement_id);
CREATE INDEX idx_pg_payment_method        ON pg_payment (payment_method);


-- ─────────────────────────────────────────────────────────────
-- pg_settlement — PG 가맹점별 일별 정산
-- ─────────────────────────────────────────────────────────────
-- 정산 배치가 target_date 의 APPROVED 결제를 가맹점별로 집계해 생성.
-- 상태 흐름: PENDING → SETTLED | FAILED
--
-- 원장 분개 (Step 2):
--   DR 현금          (1001) = total_amount
--   CR 가맹점정산부채 (2002) = net_amount
--   CR 수수료수입    (4002) = commission_amount
--
-- reference_id = 'PGSTL-{merchant_id}-{target_date}' (멱등성 키)

CREATE TABLE pg_settlement
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMPTZ(6)                          NOT NULL,
    updated_at        TIMESTAMPTZ(6)                          NOT NULL,
    merchant_id       BIGINT                                  NOT NULL,
    target_date       DATE                                    NOT NULL, -- 매출 기준일
    settlement_date   DATE                                    NOT NULL, -- 가맹점 입금일 (target_date + settlement_cycle)
    payment_count     INT                                     NOT NULL,
    total_amount      NUMERIC(20, 2)                          NOT NULL,
    commission_amount NUMERIC(20, 2)                          NOT NULL,
    net_amount        NUMERIC(20, 2)                          NOT NULL,
    currency          VARCHAR(3)                              NOT NULL DEFAULT 'KRW',
    status            VARCHAR(20)                             NOT NULL, -- PENDING / SETTLED / FAILED
    settled_at        TIMESTAMPTZ(6),
    failed_reason     VARCHAR(500),
    reference_id      VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_pg_settlement      PRIMARY KEY (id),
    CONSTRAINT uq_pg_settlement_ref  UNIQUE (reference_id)
);

CREATE INDEX idx_pg_stl_merchant        ON pg_settlement (merchant_id);
CREATE INDEX idx_pg_stl_settlement_date ON pg_settlement (settlement_date);
CREATE INDEX idx_pg_stl_target_date     ON pg_settlement (target_date);
CREATE INDEX idx_pg_stl_status          ON pg_settlement (status);
