CREATE TABLE ai_prompt
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    prompt_key  VARCHAR(255)                            NOT NULL,
    version     INTEGER                                 NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    template    TEXT                                    NOT NULL,
    model       VARCHAR(255),
    temperature DOUBLE PRECISION,
    enabled     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_ai_prompt PRIMARY KEY (id)
);