-- public.account definition
-- Drop table
-- DROP TABLE public.account;

create table public.account ( id int8 generated by default as identity( increment by 1 minvalue 1 maxvalue 9223372036854775807 start 1 cache 1 no cycle) not null,
                              created_at timestamptz(6) not null,
                              updated_at timestamptz(6) not null,
                              account_name varchar(100) not null,
                              account_number varchar(20) not null,
                              account_type varchar(20) not null,
                              available_balance numeric(20, 4) not null,
                              balance numeric(20, 4) not null,
                              currency varchar(3) not null,
                              status varchar(20) not null,
                              user_id int8 not null,
                              "version" int8 not null,
constraint account_pkey primary key (id),
constraint uq_account_number unique (account_number));
create index idx_account_user_id on
    public.account
    using btree (user_id);
