-- ============================================================
--  FX 도메인 마이그레이션
--
--  1. exchange_rate_history 테이블 생성 (이력 전용, append-only)
--  2. exchange_rate 기존 데이터 → exchange_rate_history 이관
--  3. exchange_rate 중복 제거 (pair+type 당 최신 1건만 유지)
--  4. exchange_rate 구조 변경 (UNIQUE 제약 추가, 인덱스 재구성)
--  5. fx_corridor 테이블 생성
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- 1. exchange_rate_history 생성
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.exchange_rate_history (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6)  NOT NULL,
    updated_at          timestamptz(6)  NOT NULL,
    base_currency_code  varchar(3)      NOT NULL,
    quote_currency_code varchar(3)      NOT NULL,
    rate_type           varchar(20)     NOT NULL,
    rate                numeric(18, 8)  NOT NULL,
    quoted_at           timestamptz(6)  NOT NULL,
    source              varchar(50)     NOT NULL,
    CONSTRAINT exchange_rate_history_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_erh_pair_type_at ON public.exchange_rate_history USING btree (base_currency_code, quote_currency_code, rate_type, quoted_at);
CREATE INDEX idx_erh_quoted_at    ON public.exchange_rate_history USING btree (quoted_at);


-- ────────────────────────────────────────────────────────────
-- 2. 기존 exchange_rate 데이터 → exchange_rate_history 전량 이관
-- ────────────────────────────────────────────────────────────
INSERT INTO public.exchange_rate_history (id, created_at, updated_at,
    base_currency_code, quote_currency_code, rate_type, rate, quoted_at, source)
SELECT id, created_at, updated_at,
    base_currency_code, quote_currency_code, rate_type, rate, quoted_at, source
FROM public.exchange_rate;


-- ────────────────────────────────────────────────────────────
-- 3. exchange_rate 중복 제거 — pair+type 당 최신 1건만 유지
-- ────────────────────────────────────────────────────────────
DELETE FROM public.exchange_rate
WHERE id NOT IN (
    SELECT id
    FROM (
        SELECT id,
               ROW_NUMBER() OVER (
                   PARTITION BY base_currency_code, quote_currency_code, rate_type
                   ORDER BY quoted_at DESC, id DESC
               ) AS rn
        FROM public.exchange_rate
    ) ranked
    WHERE rn = 1
);


-- ────────────────────────────────────────────────────────────
-- 4. exchange_rate 구조 변경
-- ────────────────────────────────────────────────────────────

-- 기존 인덱스 제거
DROP INDEX IF EXISTS public.idx_fx_pair_type_at;
DROP INDEX IF EXISTS public.idx_fx_quoted_at;

-- UNIQUE 제약 추가 (pair + type 당 1행 보장)
ALTER TABLE public.exchange_rate
    ADD CONSTRAINT uq_exchange_rate_pair_type
        UNIQUE (base_currency_code, quote_currency_code, rate_type);

-- 새 인덱스
CREATE INDEX idx_exchange_rate_pair ON public.exchange_rate USING btree (base_currency_code, quote_currency_code);


-- ────────────────────────────────────────────────────────────
-- 5. fx_corridor 생성
-- ────────────────────────────────────────────────────────────
CREATE TABLE public.fx_corridor (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6)  NOT NULL,
    updated_at          timestamptz(6)  NOT NULL,
    base_currency_code  varchar(3)      NOT NULL,
    quote_currency_code varchar(3)      NOT NULL,
    min_amount          numeric(20, 4)  NOT NULL,
    max_amount          numeric(20, 4)  NULL,
    daily_limit         numeric(20, 4)  NULL,
    spread_rate         numeric(8, 6)   NOT NULL,
    status              varchar(20)     NOT NULL,
    CONSTRAINT fx_corridor_pkey     PRIMARY KEY (id),
    CONSTRAINT uq_fx_corridor_pair  UNIQUE (base_currency_code, quote_currency_code)
);
CREATE INDEX idx_corridor_status ON public.fx_corridor USING btree (status);
CREATE INDEX idx_corridor_pair   ON public.fx_corridor USING btree (base_currency_code, quote_currency_code);
