-- public.account_tx definition

-- Drop table

-- DROP TABLE public.account_tx;

CREATE TABLE public.account_tx (
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   created_at timestamptz(6) NOT NULL,
                                   updated_at timestamptz(6) NOT NULL,
                                   account_id int8 NOT NULL,
                                   amount numeric(20, 4) NOT NULL,
                                   fee numeric(10, 4) NOT NULL,
                                   price numeric(20, 4) NULL,
                                   quantity numeric(20, 8) NULL,
                                   reference_id varchar(64) NULL,
                                   status varchar(20) NOT NULL,
                                   stock_id int8 NULL,
                                   tax numeric(10, 4) NOT NULL,
                                   traded_at timestamptz(6) NOT NULL,
                                   tx_type varchar(20) NOT NULL,
                                   CONSTRAINT account_tx_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_account_tx_account_id ON public.account_tx USING btree (account_id);
CREATE INDEX idx_account_tx_account_traded_at ON public.account_tx USING btree (account_id, traded_at);
CREATE INDEX idx_account_tx_stock_id ON public.account_tx USING btree (stock_id);
CREATE INDEX idx_account_tx_traded_at ON public.account_tx USING btree (traded_at);