CREATE TABLE bank
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name          VARCHAR(50)                             NOT NULL,
    national_code VARCHAR(20)                             NOT NULL,
    swift_code    VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_bank PRIMARY KEY (id)
);

ALTER TABLE bank
    ADD CONSTRAINT uc_bank_nationalcode UNIQUE (national_code);

ALTER TABLE bank
    ADD CONSTRAINT uc_bank_swiftcode UNIQUE (swift_code);