-- =====================================================================
-- billing_invoice — 청구서 (계정 단위 월별 수수료 집계)
-- =====================================================================

CREATE TABLE billing_invoice
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    account_id     BIGINT                                  NOT NULL,
    billing_period VARCHAR(7)                              NOT NULL, -- YYYY-MM
    status         VARCHAR(20)                             NOT NULL, -- DRAFT/ISSUED/PAID/OVERDUE/CANCELLED
    currency       VARCHAR(10)                             NOT NULL,
    subtotal       NUMERIC(20, 4)                          NOT NULL,
    tax_amount     NUMERIC(20, 4)                          NOT NULL,
    total_amount   NUMERIC(20, 4)                          NOT NULL,
    due_date       DATE,
    issued_at      TIMESTAMP WITHOUT TIME ZONE,
    paid_at        TIMESTAMP WITHOUT TIME ZONE,
    note           VARCHAR(500),
    CONSTRAINT pk_billing_invoice PRIMARY KEY (id)
);

CREATE INDEX idx_billing_invoice_account_id     ON billing_invoice (account_id);
CREATE INDEX idx_billing_invoice_billing_period ON billing_invoice (billing_period);
CREATE INDEX idx_billing_invoice_status         ON billing_invoice (status);

-- =====================================================================
-- 기초 데이터 — 데모 청구서 3건 (DRAFT / ISSUED / PAID)
-- =====================================================================

INSERT INTO billing_invoice (
    created_at, updated_at, account_id, billing_period, status, currency,
    subtotal, tax_amount, total_amount, due_date, issued_at, paid_at, note
)
SELECT
    now() - interval '7 days', now() - interval '7 days',
    (SELECT id FROM account ORDER BY id LIMIT 1),
    to_char(now() - interval '1 month', 'YYYY-MM'),
    'PAID', 'KRW',
    50000, 5000, 55000,
    (now() - interval '5 days')::date,
    now() - interval '7 days',
    now() - interval '4 days',
    '데모 청구서 #1 (납부 완료)'
WHERE EXISTS (SELECT 1 FROM account);

INSERT INTO billing_invoice (
    created_at, updated_at, account_id, billing_period, status, currency,
    subtotal, tax_amount, total_amount, due_date, issued_at, paid_at, note
)
SELECT
    now() - interval '3 days', now() - interval '3 days',
    (SELECT id FROM account ORDER BY id LIMIT 1),
    to_char(now(), 'YYYY-MM'),
    'ISSUED', 'KRW',
    80000, 8000, 88000,
    (now() + interval '7 days')::date,
    now() - interval '3 days',
    NULL,
    '데모 청구서 #2 (발행, 납부 대기)'
WHERE EXISTS (SELECT 1 FROM account);

INSERT INTO billing_invoice (
    created_at, updated_at, account_id, billing_period, status, currency,
    subtotal, tax_amount, total_amount, due_date, issued_at, paid_at, note
)
SELECT
    now() - interval '1 day', now() - interval '1 day',
    (SELECT id FROM account ORDER BY id LIMIT 1 OFFSET 1),
    to_char(now(), 'YYYY-MM'),
    'DRAFT', 'KRW',
    0, 0, 0,
    NULL, NULL, NULL,
    '데모 청구서 #3 (작성 중)'
WHERE (SELECT COUNT(*) FROM account) >= 2;
