CREATE TABLE account_transaction
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    account_id       BIGINT                                  NOT NULL,
    type             VARCHAR(10)                             NOT NULL,
    amount           DECIMAL(19)                             NOT NULL,
    balance_snapshot DECIMAL(19)                             NOT NULL,
    description      VARCHAR(200),
    CONSTRAINT pk_account_transaction PRIMARY KEY (id)
);

ALTER TABLE account_transaction
    ADD CONSTRAINT FK_ACCOUNT_TRANSACTION_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);