-- ============================================================
--  Insurance 도메인 DDL
--  insurance_product / insurance_policy / beneficiary
--  premium_payment  / insurance_claim
-- ============================================================

-- public.insurance_product definition
-- DROP TABLE public.insurance_product;

CREATE TABLE public.insurance_product (
    id                 int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at         timestamptz(6) NOT NULL,
    updated_at         timestamptz(6) NOT NULL,
    product_code       varchar(30)   NOT NULL,
    "name"             varchar(200)  NOT NULL,
    description        varchar(1000) NULL,
    insurance_type     varchar(20)   NOT NULL,
    base_premium       numeric(18, 2) NOT NULL,
    premium_frequency  varchar(20)   NOT NULL,
    coverage_amount    numeric(20, 2) NOT NULL,
    duration_months    int4          NOT NULL,
    currency           varchar(3)    NOT NULL,
    is_active          bool          NOT NULL,
    CONSTRAINT insurance_product_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_code        UNIQUE (product_code)
);
CREATE INDEX idx_product_type   ON public.insurance_product USING btree (insurance_type);
CREATE INDEX idx_product_active ON public.insurance_product USING btree (is_active);


-- public.insurance_policy definition
-- DROP TABLE public.insurance_policy;

CREATE TABLE public.insurance_policy (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6) NOT NULL,
    updated_at          timestamptz(6) NOT NULL,
    "version"           int8          NOT NULL,
    policy_number       varchar(30)   NOT NULL,
    product_id          int8          NOT NULL,
    user_id             int8          NOT NULL,
    insured_user_id     int8          NOT NULL,
    billing_account_id  int8          NOT NULL,
    premium             numeric(18, 2) NOT NULL,
    premium_frequency   varchar(20)   NOT NULL,
    coverage_amount     numeric(20, 2) NOT NULL,
    currency            varchar(3)    NOT NULL,
    start_date          date          NOT NULL,
    end_date            date          NOT NULL,
    next_payment_date   date          NULL,
    status              varchar(20)   NOT NULL,
    activated_at        timestamptz(6) NULL,
    terminated_at       timestamptz(6) NULL,
    CONSTRAINT insurance_policy_pkey PRIMARY KEY (id),
    CONSTRAINT uq_policy_number      UNIQUE (policy_number)
);
CREATE INDEX idx_policy_user_id    ON public.insurance_policy USING btree (user_id);
CREATE INDEX idx_policy_product_id ON public.insurance_policy USING btree (product_id);
CREATE INDEX idx_policy_status     ON public.insurance_policy USING btree (status);
CREATE INDEX idx_policy_end_date   ON public.insurance_policy USING btree (end_date);


-- public.beneficiary definition
-- DROP TABLE public.beneficiary;

CREATE TABLE public.beneficiary (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6) NOT NULL,
    updated_at          timestamptz(6) NOT NULL,
    policy_id           int8          NOT NULL,
    beneficiary_user_id int8          NULL,
    "name"              varchar(100)  NOT NULL,
    relationship        varchar(50)   NOT NULL,
    share_percent       numeric(5, 2) NOT NULL,
    beneficiary_type    varchar(20)   NOT NULL,
    CONSTRAINT beneficiary_pkey PRIMARY KEY (id),
    CONSTRAINT fk_beneficiary_policy FOREIGN KEY (policy_id) REFERENCES public.insurance_policy(id)
);
CREATE INDEX idx_beneficiary_policy_id ON public.beneficiary USING btree (policy_id);
CREATE INDEX idx_beneficiary_user_id   ON public.beneficiary USING btree (beneficiary_user_id);


-- public.premium_payment definition
-- DROP TABLE public.premium_payment;

CREATE TABLE public.premium_payment (
    id                 int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at         timestamptz(6) NOT NULL,
    updated_at         timestamptz(6) NOT NULL,
    policy_id          int8          NOT NULL,
    amount             numeric(18, 2) NOT NULL,
    currency           varchar(3)    NOT NULL,
    due_date           date          NOT NULL,
    paid_at            timestamptz(6) NULL,
    billing_account_id int8          NOT NULL,
    account_tx_id      int8          NULL,
    status             varchar(20)   NOT NULL,
    reference_id       varchar(64)   NOT NULL,
    failure_reason     varchar(200)  NULL,
    CONSTRAINT premium_payment_pkey   PRIMARY KEY (id),
    CONSTRAINT uq_premium_reference   UNIQUE (reference_id)
);
CREATE INDEX idx_premium_policy_id  ON public.premium_payment USING btree (policy_id);
CREATE INDEX idx_premium_due_date   ON public.premium_payment USING btree (due_date);
CREATE INDEX idx_premium_status     ON public.premium_payment USING btree (status);
CREATE INDEX idx_premium_account_tx ON public.premium_payment USING btree (account_tx_id);


-- public.insurance_claim definition
-- DROP TABLE public.insurance_claim;

CREATE TABLE public.insurance_claim (
    id                int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at        timestamptz(6) NOT NULL,
    updated_at        timestamptz(6) NOT NULL,
    "version"         int8          NOT NULL,
    claim_number      varchar(30)   NOT NULL,
    policy_id         int8          NOT NULL,
    claimant_user_id  int8          NOT NULL,
    event_date        date          NOT NULL,
    claim_reason      varchar(500)  NOT NULL,
    claim_amount      numeric(20, 2) NOT NULL,
    approved_amount   numeric(20, 2) NULL,
    payout_account_id int8          NULL,
    account_tx_id     int8          NULL,
    status            varchar(20)   NOT NULL,
    submitted_at      timestamptz(6) NOT NULL,
    reviewed_at       timestamptz(6) NULL,
    paid_at           timestamptz(6) NULL,
    reviewer_admin_id int8          NULL,
    review_notes      varchar(1000) NULL,
    CONSTRAINT insurance_claim_pkey PRIMARY KEY (id),
    CONSTRAINT uq_claim_number      UNIQUE (claim_number)
);
CREATE INDEX idx_claim_policy_id  ON public.insurance_claim USING btree (policy_id);
CREATE INDEX idx_claim_claimant   ON public.insurance_claim USING btree (claimant_user_id);
CREATE INDEX idx_claim_status     ON public.insurance_claim USING btree (status);
CREATE INDEX idx_claim_event_date ON public.insurance_claim USING btree (event_date);
