-- =====================================================================
-- settlement — 정산 (거래/기간 단위 금액 정산)
-- =====================================================================

CREATE TABLE settlement
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    account_id      BIGINT                                  NOT NULL,
    type            VARCHAR(30)                             NOT NULL, -- TRADE / FX / INSURANCE_PREMIUM / FEE
    settlement_date DATE                                    NOT NULL,
    status          VARCHAR(20)                             NOT NULL, -- PENDING / SETTLED / FAILED / CANCELLED
    currency        VARCHAR(10)                             NOT NULL,
    gross_amount    NUMERIC(20, 4)                          NOT NULL,
    fee_amount      NUMERIC(20, 4)                          NOT NULL,
    tax_amount      NUMERIC(20, 4)                          NOT NULL,
    net_amount      NUMERIC(20, 4)                          NOT NULL,
    reference_id    VARCHAR(64),
    note            VARCHAR(500),
    settled_at      TIMESTAMP WITHOUT TIME ZONE,
    failed_reason   VARCHAR(255),
    CONSTRAINT pk_settlement PRIMARY KEY (id)
);

CREATE INDEX idx_settlement_account_id      ON settlement (account_id);
CREATE INDEX idx_settlement_status          ON settlement (status);
CREATE INDEX idx_settlement_settlement_date ON settlement (settlement_date);
CREATE INDEX idx_settlement_reference_id    ON settlement (reference_id);

-- =====================================================================
-- 기초 데이터 — 4건 (SETTLED 2 / PENDING 1 / FAILED 1)
-- =====================================================================

-- ① 주식 체결 정산 - SETTLED
INSERT INTO settlement (
    created_at, updated_at, account_id, type, settlement_date, status, currency,
    gross_amount, fee_amount, tax_amount, net_amount, reference_id, note,
    settled_at, failed_reason
)
SELECT
    now() - interval '4 days', now() - interval '3 days',
    (SELECT id FROM account ORDER BY id LIMIT 1),
    'TRADE',
    (now() - interval '3 days')::date,
    'SETTLED', 'KRW',
    750000, 1500, 0, 748500,
    'demo-ord-001', '데모 주식 체결 정산',
    now() - interval '3 days', NULL
WHERE EXISTS (SELECT 1 FROM account)
  AND NOT EXISTS (SELECT 1 FROM settlement WHERE reference_id = 'demo-ord-001');

-- ② 외환 환전 정산 - SETTLED
INSERT INTO settlement (
    created_at, updated_at, account_id, type, settlement_date, status, currency,
    gross_amount, fee_amount, tax_amount, net_amount, reference_id, note,
    settled_at, failed_reason
)
SELECT
    now() - interval '2 days', now() - interval '2 days',
    (SELECT id FROM account ORDER BY id LIMIT 1),
    'FX',
    (now() - interval '2 days')::date,
    'SETTLED', 'USD',
    1000, 10, 0, 990,
    'demo-fx-001', '데모 USD 환전 정산',
    now() - interval '2 days', NULL
WHERE EXISTS (SELECT 1 FROM account)
  AND NOT EXISTS (SELECT 1 FROM settlement WHERE reference_id = 'demo-fx-001');

-- ③ 보험료 정산 - PENDING
INSERT INTO settlement (
    created_at, updated_at, account_id, type, settlement_date, status, currency,
    gross_amount, fee_amount, tax_amount, net_amount, reference_id, note,
    settled_at, failed_reason
)
SELECT
    now() - interval '6 hours', now() - interval '6 hours',
    (SELECT id FROM account ORDER BY id LIMIT 1 OFFSET 1),
    'INSURANCE_PREMIUM',
    now()::date,
    'PENDING', 'KRW',
    50000, 0, 0, 50000,
    'demo-prem-001', '월납 보험료 자동 정산 대기',
    NULL, NULL
WHERE (SELECT COUNT(*) FROM account) >= 2
  AND NOT EXISTS (SELECT 1 FROM settlement WHERE reference_id = 'demo-prem-001');

-- ④ 수수료 정산 - FAILED
INSERT INTO settlement (
    created_at, updated_at, account_id, type, settlement_date, status, currency,
    gross_amount, fee_amount, tax_amount, net_amount, reference_id, note,
    settled_at, failed_reason
)
SELECT
    now() - interval '1 day', now() - interval '1 day' + interval '5 minutes',
    (SELECT id FROM account ORDER BY id LIMIT 1),
    'FEE',
    (now() - interval '1 day')::date,
    'FAILED', 'KRW',
    20000, 0, 2000, 18000,
    'demo-fee-001', '수수료 정산 실패 데모',
    NULL, '잔고 부족으로 정산 실패'
WHERE EXISTS (SELECT 1 FROM account)
  AND NOT EXISTS (SELECT 1 FROM settlement WHERE reference_id = 'demo-fee-001');
