CREATE TABLE account
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    bank_id        BIGINT,
    user_id        BIGINT,
    version        BIGINT                                  NOT NULL,
    account_number VARCHAR(20)                             NOT NULL,
    owner_name     VARCHAR(50)                             NOT NULL,
    balance        DECIMAL(19, 4)                          NOT NULL,
    status         VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_accountnumber UNIQUE (account_number);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_BANK FOREIGN KEY (bank_id) REFERENCES bank (id);