-- ============================================================
--  Ledger 도메인 DDL
--  ledger_account / accounting_period / journal_entry / journal_line
-- ============================================================

-- public.ledger_account definition
-- DROP TABLE public.ledger_account;

CREATE TABLE public.ledger_account (
    id             int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at     timestamptz(6) NOT NULL,
    updated_at     timestamptz(6) NOT NULL,
    account_code   varchar(30)  NOT NULL,
    "name"         varchar(200) NOT NULL,
    category       varchar(20)  NOT NULL,
    normal_balance varchar(10)  NOT NULL,
    parent_id      int8         NULL,
    currency       varchar(3)   NOT NULL,
    is_active      bool         NOT NULL,
    description    varchar(500) NULL,
    CONSTRAINT ledger_account_pkey     PRIMARY KEY (id),
    CONSTRAINT uq_ledger_account_code  UNIQUE (account_code)
);
CREATE INDEX idx_ledger_category  ON public.ledger_account USING btree (category);
CREATE INDEX idx_ledger_parent_id ON public.ledger_account USING btree (parent_id);
CREATE INDEX idx_ledger_active    ON public.ledger_account USING btree (is_active);


-- public.accounting_period definition
-- DROP TABLE public.accounting_period;

CREATE TABLE public.accounting_period (
    id                  int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at          timestamptz(6) NOT NULL,
    updated_at          timestamptz(6) NOT NULL,
    fiscal_year         int4         NOT NULL,
    fiscal_period       int4         NOT NULL,
    start_date          date         NOT NULL,
    end_date            date         NOT NULL,
    status              varchar(20)  NOT NULL,
    closed_at           timestamptz(6) NULL,
    closed_by_admin_id  int8         NULL,
    CONSTRAINT accounting_period_pkey    PRIMARY KEY (id),
    CONSTRAINT uq_period_year_month      UNIQUE (fiscal_year, fiscal_period)
);
CREATE INDEX idx_period_status ON public.accounting_period USING btree (status);


-- public.journal_entry definition
-- DROP TABLE public.journal_entry;

CREATE TABLE public.journal_entry (
    id                     int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at             timestamptz(6) NOT NULL,
    updated_at             timestamptz(6) NOT NULL,
    "version"              int8         NOT NULL,
    journal_number         varchar(30)  NOT NULL,
    entry_date             date         NOT NULL,
    period_id              int8         NOT NULL,
    description            varchar(500) NOT NULL,
    reference_type         varchar(30)  NULL,
    reference_id           varchar(64)  NULL,
    status                 varchar(20)  NOT NULL,
    posted_at              timestamptz(6) NULL,
    reversed_by_journal_id int8         NULL,
    reverses_journal_id    int8         NULL,
    CONSTRAINT journal_entry_pkey  PRIMARY KEY (id),
    CONSTRAINT uq_journal_number   UNIQUE (journal_number)
);
CREATE INDEX idx_journal_entry_date ON public.journal_entry USING btree (entry_date);
CREATE INDEX idx_journal_period_id  ON public.journal_entry USING btree (period_id);
CREATE INDEX idx_journal_status     ON public.journal_entry USING btree (status);
CREATE INDEX idx_journal_reference  ON public.journal_entry USING btree (reference_type, reference_id);
CREATE INDEX idx_journal_posted_at  ON public.journal_entry USING btree (posted_at);


-- public.journal_line definition
-- DROP TABLE public.journal_line;

CREATE TABLE public.journal_line (
    id                int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at        timestamptz(6) NOT NULL,
    updated_at        timestamptz(6) NOT NULL,
    journal_id        int8          NOT NULL,
    line_no           int4          NOT NULL,
    ledger_account_id int8          NOT NULL,
    debit             numeric(20, 4) NOT NULL,
    credit            numeric(20, 4) NOT NULL,
    currency          varchar(3)    NOT NULL,
    description       varchar(500)  NULL,
    CONSTRAINT journal_line_pkey PRIMARY KEY (id),
    CONSTRAINT fk_journal_line_entry FOREIGN KEY (journal_id) REFERENCES public.journal_entry(id)
);
CREATE INDEX idx_line_journal_id     ON public.journal_line USING btree (journal_id);
CREATE INDEX idx_line_ledger_account ON public.journal_line USING btree (ledger_account_id);
