-- public.stock definition

-- Drop table

-- DROP TABLE public.stock;

CREATE TABLE public.stock (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              created_at timestamptz(6) NOT NULL,
                              updated_at timestamptz(6) NOT NULL,
                              currency varchar(3) NOT NULL,
                              exchange varchar(10) NOT NULL,
                              is_active bool NOT NULL,
                              last_price numeric(20, 4) NULL,
                              last_synced_at timestamptz(6) NULL,
                              market_cap numeric(24, 4) NULL,
                              "name" varchar(200) NOT NULL,
                              sector varchar(100) NULL,
                              ticker varchar(20) NOT NULL,
                              CONSTRAINT stock_pkey PRIMARY KEY (id),
                              CONSTRAINT uq_stock_ticker_exchange UNIQUE (ticker, exchange)
);
CREATE INDEX idx_stock_exchange ON public.stock USING btree (exchange);
CREATE INDEX idx_stock_is_active ON public.stock USING btree (is_active);
CREATE INDEX idx_stock_sector ON public.stock USING btree (sector);

-- public.stock_position definition

-- Drop table

-- DROP TABLE public.stock_position;

CREATE TABLE public.stock_position (
                                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                       created_at timestamptz(6) NOT NULL,
                                       updated_at timestamptz(6) NOT NULL,
                                       account_id int8 NOT NULL,
                                       realized_pnl numeric(20, 4) NOT NULL,
                                       stock_id int8 NOT NULL,
                                       total_quantity numeric(20, 8) NOT NULL,
                                       "version" int8 NOT NULL,
                                       CONSTRAINT stock_position_pkey PRIMARY KEY (id),
                                       CONSTRAINT uq_position_account_stock UNIQUE (account_id, stock_id)
);
CREATE INDEX idx_position_account_id ON public.stock_position USING btree (account_id);
CREATE INDEX idx_position_stock_id ON public.stock_position USING btree (stock_id);

-- public.position_lot definition

-- Drop table

-- DROP TABLE public.position_lot;

CREATE TABLE public.position_lot (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     created_at timestamptz(6) NOT NULL,
                                     updated_at timestamptz(6) NOT NULL,
                                     bought_at timestamptz(6) NOT NULL,
                                     buy_price numeric(20, 4) NOT NULL,
                                     buy_tx_id int8 NOT NULL,
                                     lot_status varchar(20) NOT NULL,
                                     original_quantity numeric(20, 8) NOT NULL,
                                     remaining_quantity numeric(20, 8) NOT NULL,
                                     "version" int8 NOT NULL,
                                     position_id int8 NOT NULL,
	CONSTRAINT position_lot_pkey PRIMARY KEY (id),
	CONSTRAINT fkogsk3vn43pkmipvsg5cy7up6v FOREIGN KEY (position_id) REFERENCES public.stock_position(id)
);
CREATE INDEX idx_lot_buy_tx_id ON public.position_lot USING btree (buy_tx_id);
CREATE INDEX idx_lot_position_bought_at ON public.position_lot USING btree (position_id, bought_at, id);
CREATE INDEX idx_lot_position_id ON public.position_lot USING btree (position_id);
CREATE INDEX idx_lot_status ON public.position_lot USING btree (lot_status);


-- public.lot_disposal definition

-- Drop table

-- DROP TABLE public.lot_disposal;

CREATE TABLE public.lot_disposal (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     created_at timestamptz(6) NOT NULL,
                                     updated_at timestamptz(6) NOT NULL,
                                     disposed_at timestamptz(6) NOT NULL,
                                     disposed_quantity numeric(20, 8) NOT NULL,
                                     realized_pnl numeric(20, 4) NOT NULL,
                                     sell_price numeric(20, 4) NOT NULL,
                                     sell_tx_id int8 NOT NULL,
                                     lot_id int8 NOT NULL,
                                     CONSTRAINT lot_disposal_pkey PRIMARY KEY (id),
                                     CONSTRAINT fkf2ej1eo86rk1d80x81ditdoep FOREIGN KEY (lot_id) REFERENCES public.position_lot(id)
);
CREATE INDEX idx_disposal_disposed_at ON public.lot_disposal USING btree (disposed_at);
CREATE INDEX idx_disposal_lot_id ON public.lot_disposal USING btree (lot_id);
CREATE INDEX idx_disposal_sell_tx_id ON public.lot_disposal USING btree (sell_tx_id);