# product-service: application.yml
server:
  port: 8081
spring:
  application:
    name: product-service
  threads:
    virtual:
      enabled: true     # Java 21 가상 스레드 활성화
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true        # K8s liveness/readiness용 그룹 활성화


