spring:
  threads:
    virtual:
      enabled: true

#management:
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
#    metrics:
#      export:
#        url: http://localhost:4318/v1/metrics
#        step: 10s
#    logging:
#      endpoint: http://localhost:4318/v1/logs
#  tracing:
#    sampling:
#      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY:1.0}
#  opentelemetry:
#    resource-attributes:
#      service.name: ${spring.application.name}
#      deployment.environment: ${spring.profiles.default:none}
#      service.version: ${SERVICE_VERSION:0.0.1}
#  observations:
#    annotations:
#      enabled: true

management:
  otlp:
    metrics:
      export:
        url: http://otel-lgtm:4318/v1/metrics
        step: 10s
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-lgtm:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://otel-lgtm:4318/v1/logs
    resource-attributes:
      service.name: ${spring.application.name}
      deployment.environment: ${spring.profiles.default:none}
      service.version: ${SERVICE_VERSION:0.0.1}
    observations:
      annotations:
        enabled: true

logging:
  config: "classpath:logback-spring.xml"
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
  level:
    com.revy.*: debug