spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092

  quartz:
    jdbc:
      initialize-schema: always

  batch:
    jdbc:
      initialize-schema: always

  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          name: ${spring.application.name}-local
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  show-actuator: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.revy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.kafka: DEBUG
    org.springframework.batch: DEBUG
