spring:
  datasource:
    primary:
      url: jdbc:mariadb://localhost:23306/app
      driver-class-name: org.mariadb.jdbc.Driver
      username: appuser
      password: appuser
      hikari:
        pool-name: primary
        maximum-pool-size: 10
    replica:
      url: jdbc:mariadb://localhost:33306/app
      driver-class-name: org.mariadb.jdbc.Driver
      username: appuser
      password: appuser
      hikari:
        pool-name: replica
        maximum-pool-size: 10
