CREATE TABLE ai_prompt
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP      NOT NULL,
    updated_at  TIMESTAMP      NOT NULL,
    prompt_key  VARCHAR(255)   NOT NULL,
    version     INTEGER        NOT NULL,
    role        VARCHAR(255)   NOT NULL,
    template    TEXT           NOT NULL,
    model       VARCHAR(255),
    temperature DOUBLE PRECISION,
    enabled     BOOLEAN        NOT NULL
);

CREATE UNIQUE INDEX uk_ai_prompt_key_version
    ON ai_prompt (prompt_key, version);

CREATE INDEX idx_ai_prompt_key_enabled_version
    ON ai_prompt (prompt_key, enabled, version DESC);