services:
  discovery-server:
    container_name: discovery-server
    image: msa_k8s/discovery-server
    pull_policy: never
    ports:
      - "8761:8761"
    environment:
      - SPRING_CONFIG_IMPORT=optional:classpath:application_otel-docker.yaml
      - DISCOVERY_SERVER_URL=http://discovery-server:8761/eureka/
    restart: unless-stopped

  api-gateway:
    container_name: api-gateway
    image: msa_k8s/api-gateway
    pull_policy: never
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=optional:classpath:application_otel-docker.yaml
      - DISCOVERY_SERVER_URL=http://discovery-server:8761/eureka/
    restart: unless-stopped

  user-service:
    container_name: user-service
    image: msa_k8s/user-service
    pull_policy: never
    ports:
      - "11000:11000"
    environment:
      - SPRING_CONFIG_IMPORT=optional:classpath:application_otel-docker.yaml
      - DISCOVERY_SERVER_URL=http://discovery-server:8761/eureka/
    restart: unless-stopped