package com.revy.example.domain.admin;

import com.revy.example.common.enums.ExposedEnum;

public enum AdminPermission implements ExposedEnum {
    USER_READ, USER_WRITE,
    ACCOUNT_READ, ACCOUNT_WRITE, ACCOUNT_TRANSFER,
    STOCK_READ, STOCK_WRITE,
    ORDER_READ, ORDER_WRITE, ORDER_EXECUTE, ORDER_CANCEL,
    TRADE_READ,
    FX_READ, FX_WRITE, FX_CONVERT,
    INSURANCE_READ, INSURANCE_WRITE, INSURANCE_CLAIM,
    LEDGER_READ, LEDGER_WRITE,
    ADMIN_READ, ADMIN_WRITE,
    ROLE_READ, ROLE_WRITE,
    SCHEDULER_READ, SCHEDULER_WRITE,
}
