server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    default: local
  cloud:
    gateway:
      server:
        webflux:
#          default-filters:
#            - name: CircuitBreaker
#              args:
#                name: defaultCircuitBreaker
#                fallbackUri: forward:/fallback
#            - name: Retry
#              args:
#                retries: 1
#                statuses: SERVICE_UNAVAILABLE
#                methods: POST
          routes:
#            - id: vets-service
#              uri: lb://vets-service
#              predicates:
#                - Path=/api/vet/**
#              filters:
#                - StripPrefix=2

logging:
  config: classpath:logback-spring.xml