eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,metrics,prometheus
springdoc:
  show-actuator: true

app:
  security:
    jwt:
      secret: "3e44cd44e379449d8edc3271c818fdddb6a94bdfefe22ca175b9e8e133875a793d56dced0c06dd4faecdc0d3f3d8dc06dc2b4d6fb0bf0d85cd9e2c202bc345b3"
      issuer: "auth-service"
      expires-seconds: 3600