apiVersion: v1
kind: Service
metadata:
  name: shared-server-discovery-server
  labels:
    app: shared-server-discovery-server
spec:
  ports:
    - port: 8761
      protocol: TCP
  clusterIP: None
  selector:
    app: shared-server-discovery-server
