apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: sample-k8s


build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
    - image: skaffold-k8s-helm/api-gateway
      context: .
      docker:
        dockerfile: shared-server/api-gateway/Dockerfile
    - image: skaffold-k8s-helm/discovery-server
      context: .
      docker:
        dockerfile: shared-server/discovery-server/Dockerfile
    - image: skaffold-k8s-helm/app-1
      context: .
      docker:
        dockerfile: application/app-1/Dockerfile
    - image: skaffold-k8s-helm/app-2
      context: .
      docker:
        dockerfile: application/app-2/Dockerfile
manifests:
  helm:
    releases:
      - name: api-gateway
        chartPath: k8s/helm/api-gateway
#        namespace: default
        valuesFiles:
          - k8s/helm/api-gateway/values.yaml
      - name: discovery-server
        chartPath: k8s/helm/discovery-server
#        namespace: default
        valuesFiles:
          - k8s/helm/discovery-server/values.yaml
      - name: app-1
        chartPath: k8s/helm/app-1
        #        namespace: default
        valuesFiles:
          - k8s/helm/app-1/values.yaml
      - name: app-2
        chartPath: k8s/helm/app-2
        #        namespace: default
        valuesFiles:
          - k8s/helm/app-2/values.yaml
#  rawYaml:
#    - k8s/api-gateway/*.yaml
#    - k8s/app-1/*.yaml
#    - k8s/app-2/*.yaml
#    - k8s/discovery-server/*.yaml
deploy:
  helm: {}

portForward:
  - resourceType: service
    resourceName: app-1
    port: 10000
  - resourceType: service
    resourceName: app-2
    port: 11000
  - resourceType: service
    resourceName: api-gateway
    port: 8080
  - resourceType: service
    resourceName: discovery-server
    port: 8761
