dependencies {
    api project(':module:core:core-exception')
    api project(':module:core:common')

    // Quartz - 클러스터 모드(JDBC store)로 운영
    api 'org.springframework.boot:spring-boot-starter-quartz'

    // Spring Batch - api-admin에서는 launch는 하지 않고 read/stop/abandon만 수행
    api 'org.springframework.boot:spring-boot-starter-batch'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
