version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: scdf-postgres
    environment:
      POSTGRES_DB: dataflow
      POSTGRES_USER: scdf
      POSTGRES_PASSWORD: scdf
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: scdf-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  skipper:
    image: springcloud/spring-cloud-skipper-server:2.11.5
    container_name: scdf-skipper
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dataflow
      SPRING_DATASOURCE_USERNAME: scdf
      SPRING_DATASOURCE_PASSWORD: scdf
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "7577:7577"

  dataflow:
    image: springcloud/spring-cloud-dataflow-server:3.0.0-SNAPSHOT
    container_name: scdf-server
    depends_on:
      - postgres
      - skipper
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dataflow
      SPRING_DATASOURCE_USERNAME: scdf
      SPRING_DATASOURCE_PASSWORD: scdf
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_CLOUD_DATAFLOW_FEATURES_STREAMS_ENABLED: "true"
      SPRING_CLOUD_DATAFLOW_FEATURES_TASKS_ENABLED: "true"
      SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI: http://skipper:7577/api
    ports:
      - "9393:9393"
