plugins {
    id 'java-library'
}

dependencies {
    api("com.fasterxml.jackson.core:jackson-annotations:$jacksonAnnotationsVersion")
    // Source: https://mvnrepository.com/artifact/com.github.f4b6a3/uuid-creator
    api("com.github.f4b6a3:uuid-creator:$uuidCreatorVersion")
    // Source: https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    api("org.apache.commons:commons-lang3:$commonLang3Version")
}