spring:
  threads:
    virtual:
      enabled: true

management:
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    logging:
      endpoint: http://localhost:4318/v1/logs
  tracing:
    sampling:
      probability: ${OTEL_TRACING_SAMPLING_PROBABILITY:1.0}
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      deployment.environment: ${spring.profiles.default:none}
      service.version: ${SERVICE_VERSION:1.0.0}
  observations:
    annotations:
      enabled: true

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"
  level:
    com.revy.*: debug