apiVersion: v1
kind: Service
metadata:
  name: application-app-2
  labels:
    app: application-app-2
spec:
  ports:
    - port: 11000
      protocol: TCP
  clusterIP: None
  selector:
    app: application-app-2
---