spring:
  application:
    name: kotlin-spring-quartz

  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: always

  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: app
    password: app

  jpa:
    # OSIV 비활성화
    # Controller/View 계층에서 Lazy Loading에 의존하지 않도록 함
    open-in-view: false

    hibernate:
      # 로컬 개발 초기: update
      # 운영: validate 또는 none 권장
      ddl-auto: create-drop

    # Hibernate가 출력하는 SQL을 stdout으로 직접 출력할지 여부
    # 실무에서는 false + logging 설정 사용 권장
    show-sql: false

    properties:
      hibernate:
        # Hibernate SQL 포맷팅
        format_sql: true
        # Lazy Loading 컬렉션/연관관계 조회 시
        # N+1 완화를 위한 기본 Batch Fetch 크기
        default_batch_fetch_size: 100

  threads:
    virtual:
      enabled: true