
logging:
    level:
        com.revy.*: DEBUG
        org.springframework.web: TRACE
        org.springframework.security: DEBUG
        # org.hibernate.SQL: DEBUG
        # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  security:
    jwt:
      secret: "3e44cd44e379449d8edc3271c818fdddb6a94bdfefe22ca175b9e8e133875a793d56dced0c06dd4faecdc0d3f3d8dc06dc2b4d6fb0bf0d85cd9e2c202bc345b3"
      issuer: "trading-platform"
      access-token-expiration-min: 120
      refresh-token-expiration-min: 480

server:
  port: 8080

spring:
  application:
    name: trading-platform
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:43306/trading
    username: appuser
    password: appuser
    hikari:
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379
      password: "redis1234"
      database: 0
      repositories:
        enabled: true

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
    restart:
      enabled: false
  web:
    error:
      whitelabel:
        enabled: false

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

yfinance:
  base-url: http://localhost:18000