INSERT INTO POST (CREATED_DATE, LAST_MODIFIED_DATE, TITLE, CONTENT)
SELECT
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP,
            'title-' || X,
            CAST('content-' || X AS CLOB)
FROM SYSTEM_RANGE(1, 10000);
-- FROM SYSTEM_RANGE(1, 100000000);